[project]
name = "policy-pack"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pulumi-aws>=7.0.0,<8.0.0",
    "pulumi-policy>=1.3.0,<2.0.0",
]
